In [62]:
#1: Create a null vector (zeros) of size 40
import numpy as np
A1=np.zeros(40)
print(A1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
A2=np.zeros((8,5))
print(A2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [60]:
A3=A2.copy()
A3[:,2]=1
print(A3)

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [59]:
#2. Create a vector with values ranging from 1 to 40
B1=np.arange(1,41)
print(B1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [58]:
#create in two dimenion with 8 rows and 5 columns, as array B2
B2=np.arange(1,41).reshape((8,5))
print(B2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [57]:
#create a new array B3 by adding B2 with A3 (,or increase all values of fourth column of B2 by 1)
B3=B2+A3
print(B3)


[[ 1.  2.  4.  4.  5.]
 [ 6.  7.  9.  9. 10.]
 [11. 12. 14. 14. 15.]
 [16. 17. 19. 19. 20.]
 [21. 22. 24. 24. 25.]
 [26. 27. 29. 29. 30.]
 [31. 32. 34. 34. 35.]
 [36. 37. 39. 39. 40.]]


In [56]:
#create a new array B4 with the values from B3 subtracted by 11
B4= B3-11
print(B4)

[[-10.  -9.  -7.  -7.  -6.]
 [ -5.  -4.  -2.  -2.  -1.]
 [  0.   1.   3.   3.   4.]
 [  5.   6.   8.   8.   9.]
 [ 10.  11.  13.  13.  14.]
 [ 15.  16.  18.  18.  19.]
 [ 20.  21.  23.  23.  24.]
 [ 25.  26.  28.  28.  29.]]


In [55]:
# 3. Create a 12x12 matrix and fill it with a checkerboard pattern
# first row and first column starts from 0
x=np.zeros((12,12),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)


[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]


In [54]:
#first row and first column starts from 1
x=np.ones((12,12),dtype=int)
x[1::2,::2]=0
x[::2,1::2]=0
print(x)

[[1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]]


In [53]:
#with all numbers are 1 (integer)
x=np.ones((12,12),dtype=int)
print(x)

[[1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1]]


In [52]:
 # with all numbers are 1.0 (floating-point)
 x=np.ones((12,12),dtype=float)
print(x)  

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [65]:
# 4. Create 7x7 matrixes
#P matrix with row values ranging from 0 to 6
x=np.zeros((7,7))
x +=np.arange(7)
print(x)

[[0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]]


In [66]:
# Q matrix with column values ranging from 0 to 6
x=np.zeros((7,7))
x +=np.arange(7)
y=x.transpose()
print(y)

[[0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6.]]


In [69]:
# R matrix with cumulative sum from previous row of matrix Q
x=np.zeros((7,7))
x +=np.arange(7)
y=x.transpose()
z=y.cumsum(0)
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.]
 [ 3.  3.  3.  3.  3.  3.  3.]
 [ 6.  6.  6.  6.  6.  6.  6.]
 [10. 10. 10. 10. 10. 10. 10.]
 [15. 15. 15. 15. 15. 15. 15.]
 [21. 21. 21. 21. 21. 21. 21.]]


In [75]:
# S matrix with cumulative sum from previous column of matrix Q
x=np.zeros((7,7))
x +=np.arange(7)
y=x.transpose()
t=y.cumsum(1)
print(t)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]
 [ 6. 12. 18. 24. 30. 36. 42.]]


In [76]:
# T list with cumulative sun from previous value rolled out in order of row and column from matrix Q
x=np.zeros((7,7))
x +=np.arange(7)
y=x.transpose()
t=y.cumsum()
print(t)

[  0.   0.   0.   0.   0.   0.   0.   1.   2.   3.   4.   5.   6.   7.
   9.  11.  13.  15.  17.  19.  21.  24.  27.  30.  33.  36.  39.  42.
  46.  50.  54.  58.  62.  66.  70.  75.  80.  85.  90.  95. 100. 105.
 111. 117. 123. 129. 135. 141. 147.]


In [80]:
#  5. Create a matrix, block segments, and integrations
# create matrix X of 3 rows and 12 columns of random integers range [0,100]
X=np.random.randint(100, size=(3,12))
print(X)


[[36 91 22  0 17 23 58 80 21 37 84 17]
 [70 25 94 37 22 63 33 29  6 61 24 45]
 [27 32 94 40 89 90 32 63 93 56 74 46]]


In [82]:
# create matrix XA of 3 rows and 3 columns of subset matrix of X with all rows, and the first three columns (0 to 2)
X=np.random.randint(100, size=(3,12))
print(X)
XA=X[:,0:3]
print(XA)

[[18 45 21 68 99 39 32 57 40 51 62 82]
 [93 57 39 34 12 29 87  8 26 57 85 51]
 [26 53 83 33 26 58 20 89 36 13 74 91]]
[[18 45 21]
 [93 57 39]
 [26 53 83]]


In [89]:
# create matrix XB of 3 rows and 3 columns of subset matrix of X with all rows, and the second quarter columns (3 to 5)
X=np.random.randint(100, size=(3,12))
print(X)
XB=X[:,3:6]
print(XB)



[[47 95 79 83 72 87 22 66  3  7 69 41]
 [68 18 59 12 33 90 46 85 13 50 85 10]
 [80 85 34 50 47 84 56 72  0 59 87 58]]
[[83 72 87]
 [12 33 90]
 [50 47 84]]


In [85]:
# create matrix XC of 3 rows and 3 columns of subset matrix of X with all rows, and tbe third quarter columns (6 to 8)
X=np.random.randint(100, size=(3,12))
print(X)
XC=X[:,6:9]
print(XC)


[[19 96 75 20 21 15 94 74 14 35 24 47]
 [77 22 34 53  7 43 60  9 70 55 98 37]
 [76 26 18 92 22  3 49 18 58 47 45 36]]
[[94 74 14]
 [60  9 70]
 [49 18 58]]


In [86]:
#  create matrix XD of 3 rows and 3 columns of subset matrix of X with all rows, and tbe fourth quarter columns (9 to 11)
X=np.random.randint(100, size=(3,12))
print(X)
XD=X[:,9:12]
print(XD)

[[98 26 84 41 11 32 82 56 21  7  2 97]
 [76 53 24 89 64 83 77 92 87 97  7 28]
 [88 76 42 85 68 89 30  0 55 69  7 75]]
[[ 7  2 97]
 [97  7 28]
 [69  7 75]]


In [95]:
# Create matrix Y of 3 rows and 12 columns by putting together in the order of XD XA XB XC from column index 0 to 11
X=np.random.randint(100, size=(3,12))
XA=X[:,0:3]
XB=X[:,3:6]
Y = np.concatenate((XA,XB,XC,XD)).transpose()
print(Y)


[[97 15  1 28 79 82 30  5 76  9  0 98]
 [27 10 90 60  9 17 59 43  1 19 12 42]
 [46 29 55 98  7 61 57 30 88  4 51 47]]


In [93]:
#  create matrix Z of 12 rows and 3 columns by putting together vertically in the order of XD XA XB XC
X=np.random.randint(100, size=(3,12))
XA=X[:,0:3]
XB=X[:,3:6]
XC=X[:,6:9]
XD=X[:,9:12]
Z = np.concatenate((XA,XB,XC,XD))
print(Z)

[[30 28  4]
 [70 25  0]
 [76  6 93]
 [18 16  8]
 [77 61 58]
 [36 44 66]
 [30 59 57]
 [ 5 43 30]
 [76  1 88]
 [ 9 19  4]
 [ 0 12 51]
 [98 42 47]]


In [103]:
#  6. Create the following two matrixes in the program
A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
B=np.array([[9,10,11,12],[13,14,15,16]])
print(B)
D=[[sum(a * b for a, b in zip(A_row, B_col))
                        for B_col in zip(*B)]
                                for A_row in A]
C=np.array(D)
print(C)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 35  38  41  44]
 [ 79  86  93 100]
 [123 134 145 156]
 [167 182 197 212]]
